spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/social
      username: postgres
      password: ${POSTGRES_PASSWORD_DEV}
      driverClassName: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            ddl-auto: create-drop
         show_sql: true
   ######Thymleaf#####
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
#####Redis######



##########Format SQL########
logging:
   level:
      net:
         ttddyy:
            dsproxy:
               listener: debug


######Databases#####
social:
   database:
   -  type: POSTGRES
      identifier: postgres
      url: jdbc:postgresql://localhost:5432/social
      username: postgres
      password: ${POSTGRES_PASSWORD_DEV}
      driverClassName: org.postgresql.Driver
      connections: 10
      minimumIdle: 7
      isEnabled: true
   -  type: MARIA
      identifier: maria
      url: jdbc:mariadb://localhost:3306/social
      username: root
      password: ${MARIA_PASSWORD_DEV}
      driverClassName: org.mariadb.jdbc.Driver
      connections: 10
      minimumIdle: 7
      isEnabled: true