server:
   error:
      path: /error2
   port: 9091
   servlet:
      contextPath: /social-networking-service
spring:
   application:
      name: social-networking-service
   cache:
      redis:
         enable-statistics: true
   cloud:
      config:
         discovery:
            enabled: false
   mail:
      host: smtp.gmail.com
      password: test
      port: 587
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: false
                  required: true
      test-connection: false
      username: test
   main:
      lazy-initialization: true
   mvc:
      problemdetails:
         enabled: true
   profiles:
      active: ${SPRING_PROFILE}
   security:
      user:
         name: user
         password: pass
   servlet:
      multipart:
         max-file-size: 50MB
         max-request-size: 50MB
   thymeleaf:
      cache: false
      enabled: 'true '
      prefix: classpath:/templates/
      suffix: .html

cache:
   redis:
      enable: false
   simple:
      enable: true
chatgpt:
   api-key: ''
eureka:
   client:
      fetch-registry: false
      register-with-eureka: false
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      appname: profile
      prefer-ip-address: false
java:
   home: 'Java is installed in the folder: ${JAVA_HOME}'
logging:
   level:
      com:
         netflix:
            discovery: OFF
            eureka: OFF
      org:
         springframework:
            security:
               web:
                  FilterChainProxy: DEBUG
management:
   endpoint:
      health:
         show-details: always
   endpoints:
      web:
         exposure:
            include: '*'
   info:
      env:
         enabled: true
      git:
         enabled: true
         mode: full
   health:
      show-details: always
      redis:
         enabled: false
      mail:
         enabled: false
security:
   basic:
      authorize-mode: NONE
      enabled: true
springdoc:
   show-actuator: false