spring:
   datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: create-drop
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            ddl-auto: create-drop
         show_sql: true
   ######Thymleaf#####
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
#####Redis######



##########Format SQL########
logging:
   level:
      net:
         ttddyy:
            dsproxy:
               listener: debug


######Databases#####
social:
   database:
   -  type: POSTGRES
      identifier: postgres
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
      connections: 10
      minimumIdle: 7
      isEnabled: true
   -  type: MARIA
      identifier: maria
      url: ${MARIA_URL}
      username: ${MARIADB_USER}
      password: ${MARIADB_PASSWORD}
      driverClassName: org.mariadb.jdbc.Driver
      connections: 10
      minimumIdle: 7
      isEnabled: true