######## Primary Database #######
spring:
   datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            ddl-auto: update
         show_sql: true
   ######Thymleaf#####
   thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
#####MONGO######
   mongo:
      uri: ${MONGO_DB_URI}
      db: 'social'
      enable: ${MONGO_ENABLED}
      collections: user_events


##########Format SQL########
logging:
   level:
      net:
         ttddyy:
            dsproxy:
               listener: debug


######Databases#####
social:
   database:
   -  type: POSTGRES
      identifier: postgres
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      driverClassName: org.postgresql.Driver
      connections: 10
      minimumIdle: 7
      isEnabled: true