spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      path: /h2-console
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
management:
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'